# TODO: https://github.com/vercel/turborepo/tree/main/examples/with-docker
services:
  othi:
    container_name: othi
    build:
      context: .
      dockerfile: ./apps/othi/Dockerfile
      args:
        TIPTAP_PRO_TOKEN: ${TIPTAP_PRO_TOKEN}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        EDGE_CONFIG: ${EDGE_CONFIG}
        DB_URL: ${DB_URL}
        DB_AUTH_TOKEN: ${DB_AUTH_TOKEN}
        NEXT_PUBLIC_HOST_HSR: ${NEXT_PUBLIC_HOST_HSR}
        OTHI_GITHUB_SECRET: ${OTHI_GITHUB_SECRET}
        OTHI_GITHUB_ID: ${OTHI_GITHUB_ID}
        ADMIN_IDENT: ${ADMIN_IDENT}
        AUTH_GITHUB_IDENT: ${AUTH_GITHUB_IDENT}
        UPLOADTHING_TOKEN: ${UPLOADTHING_TOKEN}
        NEXT_PUBLIC_HOST_NAS_WS: ${NEXT_PUBLIC_HOST_NAS_WS}
        GITHUB_ID: ${GITHUB_ID}
        GITHUB_SECRET: ${GITHUB_SECRET}
    restart: always
    # next start defaults to 3000
    ports:
      - 4004:3000
    networks:
      - app_network
    env_file:
      - .env

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
