# TODO: https://github.com/vercel/turborepo/tree/main/examples/with-docker
services:
  othi:
    container_name: othi
    build:
      context: .
      dockerfile: ./apps/othi/Dockerfile
      args:
        TIPTAP_PRO_TOKEN: ${TIPTAP_PRO_TOKEN}
    restart: always
    ports:
      - 4004:4004
    networks:
      - app_network
    env_file:
      - .env.production

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
