// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file atlas.proto (package dm.atlas, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { SignatureReturn, SignatureReturns } from "./atlas_pb.ts";
import { CharId } from "./shared_pb.ts";

/**
 * @generated from rpc dm.atlas.SignatureAtlasService.List
 */
export const list = {
  localName: "list",
  name: "List",
  kind: MethodKind.Unary,
  I: Empty,
  O: SignatureReturns,
  service: {
    typeName: "dm.atlas.SignatureAtlasService"
  }
} as const;

/**
 * @generated from rpc dm.atlas.SignatureAtlasService.ByCharId
 */
export const byCharId = {
  localName: "byCharId",
  name: "ByCharId",
  kind: MethodKind.Unary,
  I: CharId,
  O: SignatureReturn,
  service: {
    typeName: "dm.atlas.SignatureAtlasService"
  }
} as const;
