// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file character.proto (package dm.character, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CharId } from "./shared_pb.ts";
import { CharacterMetadata, CharacterMetadatas } from "./character_pb.ts";

/**
 * @generated from rpc dm.character.CharacterMetadataService.ById
 */
export const byId = {
  localName: "byId",
  name: "ById",
  kind: MethodKind.Unary,
  I: CharId,
  O: CharacterMetadata,
  service: {
    typeName: "dm.character.CharacterMetadataService"
  }
} as const;

/**
 * @generated from rpc dm.character.CharacterMetadataService.List
 */
export const list = {
  localName: "list",
  name: "List",
  kind: MethodKind.Unary,
  I: Empty,
  O: CharacterMetadatas,
  service: {
    typeName: "dm.character.CharacterMetadataService"
  }
} as const;
