// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file jadeestimate.proto (package jadeestimate, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { JadeEstimateCfg, JadeEstimateResponse } from "./jadeestimate_pb.ts";

/**
 * @generated from rpc jadeestimate.JadeEstimateService.Post
 */
export const post = {
  localName: "post",
  name: "Post",
  kind: MethodKind.Unary,
  I: JadeEstimateCfg,
  O: JadeEstimateResponse,
  service: {
    typeName: "jadeestimate.JadeEstimateService"
  }
} as const;
