// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file probabilityrate.proto (package probabilityrate, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { ProbabilityRatePayload, ProbabilityRateResponse } from "./probabilityrate_pb.ts";

/**
 * @generated from rpc probabilityrate.ProbabilityRateService.Post
 */
export const post = {
  localName: "post",
  name: "Post",
  kind: MethodKind.Unary,
  I: ProbabilityRatePayload,
  O: ProbabilityRateResponse,
  service: {
    typeName: "probabilityrate.ProbabilityRateService"
  }
} as const;
